name: Weekly Report
on:
  schedule:
    - cron: '10 17 * * *' 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/activity-report@v1
        with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
